name: Build, Scan, and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: myapp:latest

    - name: Install Trivy
      run: |
        echo "Installing Trivy..."
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
        echo "Trivy installed successfully!"

    - name: Scan Docker image for vulnerabilities
      run: |
        echo "Scanning Docker image for vulnerabilities..."
        ./trivy image --severity HIGH,CRITICAL myapp:latest
      shell: bash

    - name: Push Docker image to Docker Hub (only if scan passes)
      if: success()
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/nginx:latest
