name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    # Ensure the correct version of Docker (>=20.10.6) is installed
    - name: Install Docker (latest version with Docker Scan)
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io
        
        # Check Docker version and verify Docker Scan is available
        docker --version
        docker scan --version

    # Step 4: Build the Docker image (don't push yet)
    - name: Build Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: false  # Don't push yet
        tags: myapp:latest

    # Step 5: Run Docker Scan to check for vulnerabilities
    - name: Run Docker Scan
      run: |
        echo "Running Docker Scan to check for vulnerabilities..."
        docker scan myapp:latest  # Scan the image for vulnerabilities

    # Step 6: Push the image to Docker Hub if the scan passes
    - name: Push Docker image to Docker Hub (only if scan passes)
      if: success()  # Only push the image if the scan passes
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true  # Push to Docker Hub
        tags: ${{ secrets.DOCKER_USERNAME }}/nginx:latest  # Docker Hub tag
