name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password or personal access token
    
    - name: Build Docker image
      uses: docker/build-push-action@v3
      with:
        context: .  # The context is the current directory
        file: ./Dockerfile  # The Dockerfile to use
        push: false  # Don't push the image yet
        tags: myapp:latest  # Tag the local image

    - name: Run Docker Scan
      run: |
        echo "Running Docker Scan to check for vulnerabilities..."
        docker scan myapp:latest  # Scan the image for vulnerabilities

    - name: Push Docker image to Docker Hub (only if scan passes)
      if: success()  # Only push the image if the scan passes
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true  # Push the image to Docker Hub
        tags: ${{ secrets.DOCKER_USERNAME }}/nginx:latest  # Tag the image for Docker Hub
